import { StyleSheet} from 'react-native'
import COLOURS from '../../Style/Colours'
import {moderateScale,fontSizes} from "../../constants/appConstant"
export const styles = StyleSheet.create({
    LoginScreenContainer:{
        flex:1,
        backgroundColor:COLOURS.Primary
    },
    HeaderTextView:{
        marginTop:"12%",
        flexDirection:"row",
        justifyContent:"center"
    },
    HeaderText1:{
        fontSize:fontSizes.FONT34,
        color:COLOURS.Secondary,
        fontFamily:"Merienda-Bold"
    },
    HeaderText2:{
        fontSize:fontSizes.FONT34,
        color:COLOURS.Black,
        fontFamily:"Merienda-Bold"
    },
    Emailbox:{
        marginTop:moderateScale(55)
    },
    Passwordbox:{
        marginTop:moderateScale(15)
    },
    Linking:{
        flexDirection:"row",
        marginTop:"5%",
        paddingHorizontal:moderateScale(23),
        justifyContent:"space-between",
        alignItems:'center'
    },
    ClickBox:{
        flexDirection:"row",
        alignItems:"center"
    },
    ClickBox1:{
        flexDirection:"row",
        alignItems:"center"
    },
    Click:{
        height:moderateScale(20),
        width:moderateScale(20)
    },
    Rememberme:{
        fontSize:fontSizes.FONT16,
        marginLeft:moderateScale(10),
        color:COLOURS.LightGray,
    },
    Forgetpassword:{
        fontSize:fontSizes.FONT14,
        color:COLOURS.Blue
    },
    CreateAccount:{
        marginTop:"8%",
    },
    CreateAccountText:{
        fontSize:fontSizes.FONT18,
        color:COLOURS.Black,
        alignSelf:"center",
        fontWeight:"bold"
    },
    SignIn:{
        marginTop:"8%"
    },
    SignInText:{
        fontSize:fontSizes.FONT18,
        color:COLOURS.Primary,
        alignSelf:"center",
        fontWeight:"bold"
    },
    ContinueWith:{
        fontSize:fontSizes.FONT16,
        color:COLOURS.LightGray,
        alignSelf:"center",
        marginTop:"10%"
    },
    OptionBox:{
        marginTop:"12%",
        flexDirection:"row",
        justifyContent:"space-evenly",
        paddingBottom:moderateScale(20)
    }
})